"use client";

import { FaStethoscope, FaArrowRight, FaCommentMedical, FaClipboardList } from "react-icons/fa6";

interface ReportDisplayProps {
    data: {
        transcript: string;
        report: {
            patientName: string;
            location: string;
            clinicalObservation: string;
            treatmentProvided: string[];
            medicalSuppliesUsed: string[];
            patientSentiment: string;
            nextActionRequired: string;
            technicianStatus: string;
            urgency: "Routine" | "Urgent" | "Emergency";
        };
    };
}

export default function ReportDisplay({ data }: ReportDisplayProps) {
    const { report, transcript } = data;

    const handleDownload = () => {
        const reportContent = `
CLINICAL VISIT REPORT - ${new Date().toLocaleDateString()}
-------------------------------------------
PATIENT IDENTITY: ${report.patientName}
LOCATION: ${report.location}
PRIORITY LEVEL: ${report.urgency}

CLINICAL OBSERVATION:
${report.clinicalObservation}

TREATMENT PROVIDED:
${report.treatmentProvided.length > 0 ? report.treatmentProvided.map(s => `- ${s}`).join('\n') : "No specific treatment recorded"}

MEDICAL SUPPLIES USED:
${report.medicalSuppliesUsed.length > 0 ? report.medicalSuppliesUsed.map(s => `- ${s}`).join('\n') : "None recorded"}

PATIENT SENTIMENT:
${report.patientSentiment}

NEXT ACTION REQUIRED:
${report.nextActionRequired}

TECHNICIAN STATUS:
${report.technicianStatus}

-------------------------------------------
SESSION TRANSCRIPT:
"${transcript}"
-------------------------------------------
Generated by Health Job Assistant
`;
        const blob = new Blob([reportContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `Patient_Visit_Report_${report.patientName.replace(/\s+/g, '_')}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-8 animate-in fade-in slide-in-from-bottom-10 duration-1000 ease-out">
            {/* Header / Summary Card */}
            <div className="glass-card p-8 rounded-[2rem] border-l-8 border-blue-500 relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-6 opacity-5 group-hover:opacity-10 transition-opacity">
                    <FaCommentMedical className="text-8xl" />
                </div>
                
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-8">
                    <div>
                        <p className="mb-2 font-black text-blue-600 dark:text-blue-400 uppercase tracking-[0.2em] text-[10px]">Patient Identity</p>
                        <h2 className="text-3xl font-black text-slate-900 dark:text-slate-100 tracking-tight">{report.patientName}</h2>
                        <div className="flex items-center space-x-2 mt-2 text-slate-500 font-medium">
                            <span className="text-sm">{report.location}</span>
                        </div>
                    </div>
                    
                    <div className={`px-6 py-2 rounded-2xl border-2 font-black uppercase tracking-tighter text-sm ${
                        report.urgency === "Routine" ? "bg-emerald-500/10 text-emerald-600 border-emerald-500/20" : 
                        report.urgency === "Urgent" ? "bg-amber-500/10 text-amber-600 border-amber-500/20" : 
                        "bg-rose-500/10 text-rose-600 border-rose-500/20"
                    }`}>
                        {report.urgency} Priority
                    </div>
                </div>

                <div className="space-y-4">
                    <p className="text-slate-400 dark:text-slate-500 text-[10px] font-black uppercase tracking-widest">Clinical Observation</p>
                    <p className="text-slate-700 dark:text-slate-300 font-bold text-lg leading-relaxed">
                        {report.clinicalObservation}
                    </p>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Treatment & Supplies */}
                <div className="glass-card p-8 rounded-[2.5rem] space-y-8">
                    <div>
                        <div className="flex items-center space-x-3 mb-6">
                            <div className="bg-blue-500/10 p-3 rounded-2xl text-blue-600">
                                <FaStethoscope className="text-lg" />
                            </div>
                            <h3 className="font-black text-slate-900 dark:text-slate-100 tracking-tight uppercase text-sm">Treatment Provided</h3>
                        </div>
                        <div className="space-y-3">
                            {report.treatmentProvided.map((item, i) => (
                                <div key={i} className="flex items-center space-x-3 p-3 rounded-xl bg-slate-50 dark:bg-slate-800/30 border border-slate-100 dark:border-slate-700/50">
                                    <div className="w-1.5 h-1.5 bg-blue-500 rounded-full"></div>
                                    <span className="text-sm font-semibold text-slate-700 dark:text-slate-300">{item}</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div>
                        <div className="flex items-center space-x-3 mb-6">
                            <div className="bg-sky-500/10 p-3 rounded-2xl text-sky-600">
                                <FaClipboardList className="text-lg" />
                            </div>
                            <h3 className="font-black text-slate-900 dark:text-slate-100 tracking-tight uppercase text-sm">Supplies Used</h3>
                        </div>
                        <div className="flex flex-wrap gap-2">
                            {report.medicalSuppliesUsed.map((item, i) => (
                                <span key={i} className="px-3 py-1.5 bg-slate-100 dark:bg-slate-800 rounded-lg text-xs font-bold text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700">
                                    {item}
                                </span>
                            ))}
                        </div>
                    </div>
                </div>

                {/* Sentiment & Next Action */}
                <div className="space-y-6">
                    <div className="glass-card p-8 rounded-[2.5rem] bg-gradient-to-br from-white/80 to-slate-50/50 dark:from-slate-900/80 dark:to-slate-800/50">
                        <div className="flex items-center space-x-3 mb-4">
                            <span className="text-slate-400 dark:text-slate-500 text-[10px] font-black uppercase tracking-widest">Patient Sentiment</span>
                        </div>
                        <p className="text-slate-900 dark:text-slate-100 font-black text-xl italic tracking-tight">
                            &quot;{report.patientSentiment}&quot;
                        </p>
                    </div>

                    <div className="glass-card p-8 rounded-[2.5rem] border-2 border-blue-500/20 bg-blue-500/5">
                        <div className="flex items-center space-x-3 mb-4">
                            <div className="p-2 bg-blue-500 rounded-lg text-white">
                                <FaArrowRight className="text-xs" />
                            </div>
                            <span className="text-blue-600 dark:text-blue-400 text-[10px] font-black uppercase tracking-widest">Next Action Required</span>
                        </div>
                        <p className="text-slate-900 dark:text-slate-100 font-black text-lg">
                            {report.nextActionRequired}
                        </p>
                    </div>

                    <div className="glass-card p-6 rounded-3xl flex items-center justify-between border border-slate-200 dark:border-slate-800">
                        <div>
                            <p className="text-slate-400 dark:text-slate-500 text-[10px] font-black uppercase tracking-widest mb-1">Nurse Status</p>
                            <p className="text-slate-800 dark:text-slate-200 font-bold text-sm tracking-tight">{report.technicianStatus}</p>
                        </div>
                        <div className="w-3 h-3 bg-emerald-500 rounded-full animate-pulse shadow-[0_0_10px_rgba(16,185,129,0.5)]"></div>
                    </div>
                </div>
            </div>

            {/* Transcript Accordion (Simple version for premium look) */}
            <div className="glass-card p-6 rounded-2xl border border-slate-200/50 dark:border-slate-700/50 mt-12 bg-slate-50/30 dark:bg-transparent">
                <details className="group">
                    <summary className="list-none cursor-pointer flex items-center justify-between">
                        <span className="text-slate-400 dark:text-slate-500 text-[10px] font-black uppercase tracking-widest">Raw Session Transcript</span>
                        <div className="text-slate-400 group-open:rotate-180 transition-transform duration-300">
                            <FaArrowRight className="rotate-90" />
                        </div>
                    </summary>
                    <div className="mt-4 p-4 rounded-xl bg-white/50 dark:bg-slate-900/50 text-slate-500 dark:text-slate-400 text-sm italic leading-relaxed border border-slate-100 dark:border-slate-800">
                        &quot;{transcript}&quot;
                    </div>
                </details>
            </div>

            <div className="flex items-center justify-center pt-8">
                <button 
                    onClick={handleDownload}
                    className="flex items-center space-x-3 px-10 py-5 bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-[2rem] font-black tracking-tight hover:scale-105 active:scale-95 transition-all shadow-2xl shadow-slate-900/20 dark:shadow-white/10 group"
                >
                    <span>Export Patient Visit Report</span>
                    <FaArrowRight className="group-hover:translate-x-1 transition-transform" />
                </button>
            </div>
        </div>
    );
}
